version: '3.5'
services:

  java-development:
    image: ${JAVA_DEVELOPMENT_IMAGE:-eventuateio/eventuate-tram-sagas-examples-customers-and-orders-java-development:latest}
    volumes:
      - .:/eventuate-tram-sagas-examples-customers-and-orders-java-development
      - dot-gradle:/root/.gradle
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  dot-gradle:
